apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bootstrap/namespaces.yaml
  - bootstrap/imagestream.yaml
  - bootstrap/rbac.yaml
  - tekton/focus-time-timer-pipeline.yaml
  - tekton/focus-time-timer-listener-route.yaml
  - argocd/focus-time-timer-application.yaml
